---
title: "Homework 5"
author: "Rose Killian"
output: github_document
---

### Loading libraries and settings

```{r message= FALSE}
library(tidyverse)
library(p8105.datasets)
library(viridis)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

```

# Problem 1

### Data import and cleaning

```{r}
homicide_df = 
  read_csv("./data/homicide-data.csv", na = c("", "Unknown")) %>% 
  mutate(
    city_state = str_c(city, state),
    resolution = case_when(
      disposition == "Closed without arrest" ~ "unsolved",
      disposition == "Open/No arrest" ~ "unsolved",
      disposition == "Closed by arrest" ~ "solved"
  )) %>% 
  relocate(city_state) %>% 
  filter(city_state != "TulsaAL")
```

### Baltimore, MD:

```{r}
baltimore_df = 
  homicide_df %>% 
  filter(city_state == "BaltimoreMD")

baltimore_summary = 
  baltimore_df %>% 
  summarise(
    unsolved = sum(resolution == "unsolved"),
    n = n()
  )


baltimore_test = 
  prop.test(
    x = baltimore_summary %>% pull(unsolved),
    n = baltimore_summary %>% pull(n))

baltimore_test %>% 
  broom::tidy()
```

### Writing a function and testing it:

```{r}
prop_test_function = function(city_df) {
  
  city_summary = 
    city_df %>% 
    summarise(
      unsolved = sum(resolution == "unsolved"),
      n = n()
  )

  city_test = 
    prop.test(
      x = city_summary %>% pull(unsolved),
      n = city_summary %>% pull(n))
  
  return(city_test)
}

prop_test_function(baltimore_df)

homicide_df %>% 
  filter(city_state == "AlbuquerqueNM") %>% 
  prop_test_function()
```

### Iterating across cities

```{r}
results_df = 
  homicide_df %>% 
  nest(data = uid:resolution) %>% 
  mutate(
    test_results = map(data, prop_test_function),
    tidy_results = map(test_results, broom::tidy)
  ) %>% 
  select(city_state, tidy_results) %>% 
  unnest(tidy_results) %>% 
  select(city_state, estimate, starts_with("conf"))
```

### Plotting

```{r}
results_df %>% 
  mutate(city_state = fct_reorder(city_state, estimate)) %>% 
  ggplot(aes(x = city_state, y = estimate)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```

# Problem 2

```{r}
p2_df =
  tibble(
    file = list.files("./data/P2/", full.names = T)) %>%
    mutate(data = map(file, read_csv)) %>% 
    unnest(data) %>% 
    mutate(
      file = str_remove(file, "\\./data/P2/"),
      group = str_remove(file, "\\.csv"),
      id = row_number(),
      arm = str_remove(group, "_[0-9][0-9]")) %>%
    pivot_longer(
      week_1:week_8,
      names_to = "week",
      names_prefix = "week_",
      values_to = "data"
    ) %>% 
    select(id, arm, week, data) 

p2_df %>% 
  ggplot(aes(x = week, y = data, group = id, color = arm)) +
  geom_line()
```

While the two groups appear to start at similar values, over time the average values for the experimental arm appear to increase while the values for the control arm stay roughly the same. 

# Problem 3

### Setup

```{r}
set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))
```